config/routes.rb
MyGists::Application.routes.draw do
  resources :gists
  root :to => 'gists#index'

end

app/models/gist.rb
class Gist < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]

  # GET /gists
  # GET /gists.json
  def index
    #@gists = Gist.all
    @gists = Gist.paginate(page: params[:page], per_page: 8)
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gist }
      else
        format.html { render action: 'new' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:snippet, :lang, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>

<% 
b=[]
a=Pygments::Lexer.all.select{|y| !(y.filenames.empty?)}.map{|x|[x.name.downcase, x.filenames.first.gsub('*','')]}.sort
a.flatten.select.with_index{|a,i| (i+1) % 2 == 1}.each { |e| 
  b.push(e) }
 %>

  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="field">
    <%= f.label :snippet %><br>
    <%= f.text_area :snippet %>
  </div>
  <div class="field">
    <%= f.label :lang %>:<br>
   <%= f.select(:lang, b) %>
  
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= 

    f.submit(class:'btn btn-success')

    %>
  </div>
  <%= link_to 'Back', gists_path,class:'btn btn-default' %>
  <%= link_to 'Show', @gist ,class:'btn btn-default'%>
  </div>
<% end %>

app/views/gists/_index.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">My Gists</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/gists">Home</a></li>
            <li><a href="http://www.github.com/jcimoch">My Github</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
      </div>

      <div class="container" >

<div class="jumbotron" style="margin-top:80px;">
        <h1>My Gists</h1>
        <p>Aplikacja na zaliczenie laboratoriów Architektury Serwisów Internetowych</p>
        <p>prowadzący zajęcia dr W.Bzyl </p>
        <p>
          <%= link_to 'New Gist', new_gist_path, class:'btn btn-primary btn-lg' %>
        </p>
</div>

app/views/gists/edit.html.erb
<%= render 'index' %>
<h1>Editing gist</h1>

<%= render 'form' %>

app/views/gists/index.html.erb
<%= render 'index' %>

<div style="width:300px;margin: 0 auto;"><h3><%= will_paginate @gists  %></h3> </div>
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Snippet Preview</th>
      <th>Lang</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

 
    <% @gists.each do |gist| %>
      <tr>
        <td><%= raw Pygments.highlight(gist.snippet.squish[0,30]+" ... ", lexer: gist.lang)%></td>
        <td><h4><%= gist.lang %></h4></td>
        <td><%= gist.description %></td>
        <td><%=link_to 'Show Whole', gist,class:'btn btn-success' %>
        <%= link_to 'Edit', edit_gist_path(gist),class:'btn btn-primary' %>
        <%= link_to 'Destroy', gist, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  
</table>


</div>
<br>



</div>

app/views/gists/new.html.erb
<%= render 'index' %>


<%= render 'form' %>


</div>

app/views/gists/show.html.erb
<%= render 'index' %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Snippet:</strong>
</p>

<%= raw Pygments.highlight(@gist.snippet, lexer: @gist.lang )%>

<p>
  <strong>Lang:</strong>
 <h4> <%= @gist.lang %> </h4>
</p>

<p>
  <strong>Description:</strong>
 <h4> <%= @gist.description %> </h4>
</p>

<%= link_to 'Edit', edit_gist_path(@gist),class:'btn btn-primary' %> |
<%= link_to 'Back', gists_path,class:'btn btn-default' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGists</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>